name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update stable
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v1

    - run: rustup component add rustfmt clippy

    - run: cargo fmt -- --check
    - run: cargo clippy

    - run: cargo doc
